name: Actualización mensual de trending

on:
  schedule:
    - cron: '0 8 1 * *'  # El primer día de cada mes a las 8:00 UTC
  workflow_dispatch:

jobs:
  trending_monthly:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar requests
        run: pip install requests

      - name: Ejecutar script mensual
        run: python generate_monthly.py

      - name: Commit y push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git add trending_monthly.md
          if git diff --staged --quiet; then
            echo "No hay cambios para commitear"
          else
            git commit -m "chore: actualización mensual de trending"
            git pull --rebase
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
