name: Actualización semanal de trending

on:
  schedule:
    - cron: '0 8 * * 1'  # Cada lunes a las 8:00 UTC
  workflow_dispatch:

jobs:
  trending_weekly:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Instalar requests
        run: pip install requests

      - name: Ejecutar script semanal
        run: python generate_weekly.py

      - name: Commit y push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
          git add trending_weekly.md
          if git diff --staged --quiet; then
            echo "No hay cambios para commitear"
          else
            git commit -m "chore: actualización semanal de trending"
            git pull --rebase
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
